#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application;
use Clat\Command\{
    Hello,
    Ls
};

//require __DIR__ . '/vendor/autoload.php';

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application('Simple command-line app', '1.0');

$app->add(new Hello);
$app->add(new Ls);

$app->run();